M48
; DRILL file {KiCad 8.0.3} date 2024-06-28T16:48:34+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-28T16:48:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X4.79Y-5.65
X4.8Y-4.44
X4.83Y-3.19
X5.18Y-1.9
X5.53Y-3.19
X5.56Y-4.44
X5.57Y-5.65
T2
X5.18Y-2.2175
M30
