M48
; DRILL file {KiCad 8.0.2} date 2024-05-26T17:51:28+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-26T17:51:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X4.21Y-3.68
X4.51Y-3.68
T2
X4.3Y-3.5
X4.4Y-3.5
M30
